my_portfolio/models.py
import uuid
from datetime import datetime


class Visitor:
    def __init__(self, message):
        self.message = message
        self.id = uuid.uuid4().hex
        self.timestamp = datetime.utcnow()

    def to_dict(self):
        return {
            '_id': self.id,
            'message': self.message,
            'timestamp': self.timestamp.strftime('%d-%b-%Y at %H:%M:%S')
        }

my_portfolio/routes/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms.validators import DataRequired


class ContactForm(FlaskForm):
    recaptcha = RecaptchaField(validators=[DataRequired()])

my_portfolio/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from flask.cli import load_dotenv
from pymongo import MongoClient
from my_portfolio.config import Config

# from flask_pymongo import PyMongo

bootstrap = Bootstrap5()

load_dotenv()

# mongo = PyMongo()
client = MongoClient(Config.MONGO_URI)
db = client.portfolio_visitors


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    bootstrap.init_app(app)

    #  wrap the code that is causing the error in a with app.app_context():
    # with app.app_context():

    # LOAD the default db from the URI
    with app.app_context():
        app.db = db
        from my_portfolio.errors.handlers import errors
        from my_portfolio.routes.routes import pages, mail

        # initialize the app with the extension mail
        mail.init_app(app)

        app.register_blueprint(pages)
        app.register_blueprint(errors)

    return app

my_portfolio/routes/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, jsonify, abort, send_from_directory, current_app, flash, \
    redirect, url_for
from flask.cli import load_dotenv
from flask_mail import Mail, Message
from my_portfolio.config import Config
from my_portfolio.models import Visitor
from my_portfolio.projects.projects import projects

pages = Blueprint("pages", __name__, template_folder="templates", static_folder="static")

current_year = datetime.now().year

load_dotenv()
mail = Mail()


@pages.context_processor
def inject_current_year():
    """use global constants in jinja (don't need to inject each one for every template)"""
    return {"year": current_year, "date_of_birth": 1987, "recaptcha_site_key": Config.RECAPTCHA_PUBLIC_KEY,
            "recaptcha_secret_key": Config.RECAPTCHA_PRIVATE_KEY}


@pages.route("/")
def index():
    message = f"A person has visited your website."

    # Sending mail notification
    subject = "Someone has Consulted your home website"
    msg = Message(subject, recipients=[Config.MAIL_USERNAME])
    msg.body = f"Subject: New Message: {message}!"
    try:
        mail.send(msg)

        visitor = Visitor(message=message)
        current_app.db.visitors.insert_one(visitor.to_dict())

    except Exception as e:
        print(str(e))

    return render_template("index.html")


@pages.route("/portfolio/<int:i>")
def portfolio_details(i):
    """returns each HTML page according to the desired project number i"""
    if i - 1 not in range(len(projects)):
        abort(404)
    return render_template("portfolio-details.html", project=projects[i - 1])


@pages.route('/resume')
def resume():
    return render_template("resume.html")


@pages.route('/resume/Heni Bouafia-fr')
def download():
    """ download the resume from the directory"""

    message = f"A person has Downloaded french resume"

    subject = "Someone has Consulted your French resume"
    msg = Message(subject, recipients=[Config.MAIL_USERNAME])
    msg.body = f"Subject: New Message: {message}!"
    visitor = Visitor(message=message)
    current_app.db.visitors.insert_one(visitor.to_dict())
    try:
        mail.send(msg)

        return send_from_directory(directory="static", path="files/Resume-Heni Bouafia-fr.pdf", as_attachment=False)
    except Exception as e:
        return str(e)


@pages.route('/resume/download-en')
def download_en_resume():
    """ download the resume from the directory"""

    message = f"A person has Downloaded English resume"

    # Sending mail notification
    subject = "Someone has Consulted your English resume"
    msg = Message(subject, recipients=[Config.MAIL_USERNAME])
    msg.body = f"Subject: New Message: {message}!"
    visitor = Visitor(message=message)
    current_app.db.visitors.insert_one(visitor.to_dict())
    try:
        mail.send(msg)

        return send_from_directory(directory="static", path="files/Resume-Heni Bouafia-en.pdf", as_attachment=False)
    except Exception as e:
        return str(e)


@pages.route("/contact/", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        subject = request.form.get("subject")
        message_body = request.form.get("message")

        message = f"A person has sent you a message!"

        # Sending mail notification
        msg = Message(subject, recipients=[Config.MAIL_USERNAME])
        msg.body = f"Subject: New Message: {message}!\n\nName: {name}\nEmail: {email}\nMessage: {message_body}"
        visitor = Visitor(message=message)
        current_app.db.visitors.insert_one(visitor.to_dict())
        try:
            mail.send(msg)
            return jsonify({"success": True}), 200
        except Exception as e:
            print(str(e))
            return jsonify({"success": False, "errors": ["An error occurred while sending the message. Please try "
                                                         "again later."]}), 404


@pages.route(f"{Config.ADMIN_URL}", methods=["GET", "POST"])
def admin_interface():
    page = int(request.args.get('page', 1))
    per_page = 15
    offset = (page - 1) * per_page
    total_visitors = current_app.db.visitors.count_documents({})
    num_pages = (total_visitors + per_page - 1) // per_page
    visitors = current_app.db.visitors.find().sort("timestamp", -1).skip(offset).limit(per_page)
    return render_template("admin.html", visitors=visitors, page=page, num_pages=num_pages)


@pages.route(f"{Config.ADMIN_URL}/delete-visitor/<identity>", methods=["GET", "POST"])
def delete_visitor(identity):
    current_app.db.visitors.delete_one({"_id": identity})
    flash("Visitor deleted successfully", "success")
    return redirect(url_for("pages.admin_interface"))

my_portfolio/templates/admin.html
{% extends "navigation.html" %}
{% block content %}
    <div class="container">
        <h1 class="text-center mb-5">Visitors</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover mx-auto text-center">
                <thead>
                    <tr>
                        <th class="text-center">Id</th>
                        <th class="text-center">Message</th>
                        <th class="text-center">Timestamp</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for visitor in visitors %}
                        <tr>
                            <td class="text-center">{{ visitor['_id'] }}</td>
                            <td>{{ visitor['message'] }}</td>
                            <td class="text-center">{{ visitor['timestamp'] }}</td>
                            <td class="text-center">
                                <form action="{{ url_for('pages.delete_visitor', identity=visitor._id) }}" method="POST">
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center mt-4">
            <nav>
                <ul class="pagination">
                    {% if page == 1 %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('pages.admin_interface', page=page-1) }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for p in range(1, num_pages+1) %}
                        {% if p == page %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="#">{{ p }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for('pages.admin_interface', page=p) }}">{{ p }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page == num_pages %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ url_for('pages.admin_interface', page=page+1) }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

my_portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title> {% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">


  <!-- Favicons -->
  <link href="{{ url_for('static', filename='assets/img/faviconheni.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/faviconheni.png') }}" rel="apple-touch-icon">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='assets/vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">


</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="{{ url_for('static', filename='assets/img/profile-img.jpg') }}" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="{{ url_for('pages.index') }}">Heni Bouafia</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="https://twitter.com/HeniBouafia" class="twitter" target="_blank"><i class="bx bxl-twitter"></i></a>
          <a href="https://www.facebook.com/heni.bouafia" class="facebook" target="_blank"><i class="bx bxl-facebook"></i></a>
          <a href="https://www.instagram.com/hanaw.heni/?fbclid=IwAR37lmq_BK05m-Msribgrp0Y4zYJBS-JYrwF0vrmKvQIafGw2TgEyO72nLY" class="instagram" target="_blank"><i class="bx bxl-instagram"></i></a>
          <a href="https://github.com/Hanawvic/" class="google-plus" target="_blank"><i class="bx bxl-github"></i></a>
          <a href="https://www.linkedin.com/in/heni-bouafia-0b792868/?locale=en_US" class="linkedin" target="_blank"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="{{ url_for('pages.index') }}#hero" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="{{ url_for('pages.index') }}#about" class="nav-link scrollto"><i class="bx bx-user"></i> <span>About</span></a></li>
          <li><a href="{{ url_for('pages.index') }}#resume" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
          <li><a href="{{ url_for('pages.index') }}#portfolio" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
          <li><a href="{{ url_for('pages.index') }}#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a></li>
          <li><a href="{{ url_for('pages.index') }}#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
          <li><a href="{{ url_for('pages.resume') }}" class="nav-link scrollto" target="_blank"><i class="bx bx-download"></i> <span>Download</span></a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

{% block content %}
{% endblock %}

   <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright 2023 - {{ year }} <strong><span>iPORTFOLIO</span></strong>
      </div>
      <div class="credits">
        Designed by <a href="{{ url_for('pages.index') }}">HENI BOUAFIA</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='assets/vendor/purecounter/purecounter_vanilla.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/aos/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/typed.js/typed.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/waypoints/noframework.waypoints.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/flask-email-form/validate.js') }}"></script>

  <!--Google recaptcha api-->
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  <!--Secret Key env var to javascript from HTML-->
   <script>
    var RECAPTCHA_SECRET_KEY = '{{ recaptcha_secret_key }}';
  </script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>


</body>

</html>

my_portfolio/templates/inner-page.html
{% extends 'base.html' %}

{% block title %} Inner Page {% endblock %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Inner Page</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

{% endblock %}

my_portfolio/templates/navigation.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title> Admin Interface</title>
  <meta content="" name="description">
  <meta content="" name="keywords">


  <!-- Favicons -->
  <link href="{{ url_for('static', filename='assets/img/faviconheni.png') }}" rel="icon">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">
       <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}

</head>
<body>

<!-- Navigation -->
<div class="container">
 <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary" style="background-color: #CFD8DC;" id="mainNav">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('pages.index') }}">Heni Bouafia</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('pages.index') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.index') }}#about">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.index') }}#portfolio">Portfolio</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.index') }}#contact">Contact</a>
        </li>
      </ul>
      <form class="d-flex">
        <button class="btn btn-sm btn-outline-success me-2" type="button"><a class="nav-link" href="{{ url_for('pages.download_en_resume') }}" target="blanck">Download English</a></button>
        <button class="btn btn-sm btn-outline-primary" type="button"><a class="nav-link" href="{{ url_for('pages.download') }}" target="blanck">Download French</a></button>
      </form>
    </div>
  </div>
</nav>
</div>
<br>
<br> <br> <br> <br>
{% block content %}
{% endblock %}

</body>
</html>

my_portfolio/templates/portfolio-details.html
{% extends 'base.html' %}

{% block title %} Portfolio Details {% endblock %}
{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Portfoio Details</h2>
          <ol>
            <li><a href="{{ url_for('pages.index') }}">Home</a></li>
            <li>Portfoio Details</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->

    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename=project['img1']) }}" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename=project['img2']) }}" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename=project['img3']) }}" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong>: {{ project['category'] }}</li>
                <li><strong>Client</strong>: {{ project['client'] }}</li>
                <li><strong>Project date</strong>: {{ project['date'] }}</li>
                {% if project.url %}
               <li><strong>Project URL</strong>: <a href="{{ project['url'] }}" target="blank">{{ project['url_name'] }}</a></li>
                {% endif %}
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>Description</h2>
              <p>
                {{ project['description'] | safe }}
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

{% endblock %}